### ISSUE TITLE
Missing link to deployed version

### ISSUE THREAD

**Issue by linusblom** [chas-academy/08-api-mashup-jonastore#1]
Please provide link to deployed version in README.md

**Comment by jonastore** [comment]
I'm sorry for the late reply, but i can't seem to upload a functioning version of the website. The uploaded version is just a static page without any connection to the api. Might this is a problem with the build when running yarn?

**Comment by linusblom** [comment]
I can't find any `"build": "webpack"` script in `package.json`. I tried and added this myself and deployed your site to http://gentle-transport.surge.sh/ and it work great.
